version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: sepdrive-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    image: sepdrive-frontend
    ports:
      - "3000:3000"
